%% Mermaid mindmap: piano IP sintetico
mindmap
  root((Piano IP - Sede + Campo))
    Sede (10.10.0.0/16)
      VLAN10 Ticketing (10.10.10.0/24)
      VLAN20 Video (10.10.20.0/24)
      VLAN30 IoT (10.10.30.0/24)
      VLAN40 Mgmt (10.10.40.0/24)
      VLAN50 WiFi Staff (10.10.50.0/24)
      VLAN60 DMZ (10.10.60.0/24)
    VPN Remoti
      Dispositivi azionabili (10.20.10.0/24)
      Telecamere (10.20.20.0/24)
      Totem (10.20.30.0/24)
      Staff mobile (10.20.40.0/24)
